<a href="https://colab.research.google.com/github/pennyLiu32/Tibame/blob/main/pytjon%E6%9C%80%E5%BE%8C%E4%B8%80%E5%A0%82.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- 從無到有的表格
    - JSON -> Dataframe
    - JSON: [{}, {}, {}]

In [8]:
import urllib.request as req
import bs4 as bs

def download_page(page):
  url = f"https://tabelog.com/tw/kagoshima/rstLst/{page}/"
  resp = req.urlopen(url)
  content = resp.read()
  html = bs.BeautifulSoup(content)
  rs = html.find_all("div", {"class":"list-rst__body"})

  # 準備一個table
  table = []
  for r in rs:
    name = r.find("a", {"class":"list-rst__rst-name-target"})
    area_genre = r.find("div", {"class":"list-rst__area-genre"})
    rating = r.find("span", {"class":"list-rst__rating-val"})
    prices = r.find_all("span", {"class":"c-rating-v3__val"})
    lunch_price = prices[1]
    dinner_price = prices[0]
    holiday = r.find("span", {"class":"list-rst__holiday-text"})

    name_href = name["href"]
    name_text = name.get_text()
    area_genre_text = area_genre.get_text().strip()
    if rating:
      rating_text = rating.get_text()
    else:
      rating_text = None
    lunch_price_text = lunch_price.get_text().strip()
    dinner_price_text = dinner_price.get_text().strip()
    holiday_text = holiday.get_text().strip()

    # 每一筆資料都是一個字典
    data = {
      "rating": rating_text,
      "name": name_text,
      "link": name_href,
      "area_genre": area_genre_text,
      "price_lunch": lunch_price_text,
      "price_dinner": dinner_price_text,
      "holiday": holiday_text,
    }
    table.append(data)

  return table
download_page(2)

[{'rating': '3.39',
  'name': '燒酎 酒々藏',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46000160/',
  'area_genre': '天文館通車站 189m / 居酒屋 (酒館), 海鮮, 郷土料理',
  'price_lunch': '-',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'holiday': '星期日'},
 {'rating': '3.17',
  'name': 'Higoya 鹿兒島本店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46005692/',
  'area_genre': '天文館通車站 219m / 居酒屋 (酒館), 豬肉涮涮鍋',
  'price_lunch': '-',
  'price_dinner': 'JPY 5,000 - JPY 5,999',
  'holiday': '星期日'},
 {'rating': '3.54',
  'name': '吾愛人 中央站東口店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46008602/',
  'area_genre': '高見橋車站 45m / 居酒屋 (酒館), 涮涮鍋, 炸豬排',
  'price_lunch': '-',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '星期一'},
 {'rating': '3.31',
  'name': '魚菜屋 朝次郎 AMU PLAZA鹿兒島店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46000107/',
  'area_genre': '鹿兒島中央站前車站 130m / 居酒屋 (酒館), 海鮮, 海鮮蓋飯',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 2,000 - JPY 2,999',
  'holiday': '-'},
 {'rating': '3.29',
  'name': '薩摩 黑豬百寛',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46003354/',
  'area_genre': '鹿兒島中央車站 289m / 居酒屋 (酒館), 涮涮鍋, 海鮮',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.06',
  'name': '日本料理 Minato',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46014700/',
  'area_genre': '郡元車站 1285m / 日本料理, 鰻魚, 郷土料理',
  'price_lunch': 'JPY 3,000 - JPY 3,999',
  'price_dinner': 'JPY 5,000 - JPY 5,999',
  'holiday': '-'},
 {'rating': None,
  'name': '近江牛 Horumon 畜産Sudaku 國分中央店',
  'link': 'https://tabelog.com/tw/kagoshima/A4603/A460301/46018930/',
  'area_genre': '國分車站 651m / 燒肉, 內臟類, 居酒屋 (酒館)',
  'price_lunch': '-',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.54',
  'name': 'Yakushimademinshuku yatteimashita',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46014701/',
  'area_genre': '天文館通車站 132m / 居酒屋 (酒館), 海鮮, 郷土料理',
  'price_lunch': '-',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.40',
  'name': '吾愛人 中央驛西口店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46003936/',
  'area_genre': '鹿兒島中央車站 212m / 涮涮鍋, 郷土料理, 居酒屋 (酒館)',
  'price_lunch': '-',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '星期日'},
 {'rating': '3.07',
  'name': '鹿兒島劇場',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46017452/',
  'area_genre': '天文館通車站 210m / 居酒屋 (酒館), 海鮮, 涮涮鍋',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': 'JPY 2,000 - JPY 2,999',
  'holiday': '-'},
 {'rating': '3.56',
  'name': '太郎壽司',
  'link': 'https://tabelog.com/tw/kagoshima/A4602/A460203/46002327/',
  'area_genre': '阿久根車站 310m / 壽司, 海鮮, 鰻魚',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.61',
  'name': '炭火燒烤魚與、土鍋煮飯。定食屋 Ochawan',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46018052/',
  'area_genre': '天文館通車站 192m / 食堂, 酒店, 日本料理',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': '-',
  'holiday': '-'},
 {'rating': '3.07',
  'name': '黑毛和牛專門店 牛排＆肉壽司 Kirishima牧場 天文館店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46014710/',
  'area_genre': '天文館通車站 78m / 牛排, 壽司',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': 'JPY 6,000 - JPY 7,999',
  'holiday': '-'},
 {'rating': '3.01',
  'name': '中央町 貴良',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46013756/',
  'area_genre': '都通車站 109m / 日本料理',
  'price_lunch': 'JPY 8,000 - JPY 9,999',
  'price_dinner': 'JPY 15,000 - JPY 19,999',
  'holiday': '-'},
 {'rating': '3.06',
  'name': '炭火燒肉內臟 Yokozuna Sanshirou 天文館店',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46015289/',
  'area_genre': '天文館通車站 240m / 燒肉, 居酒屋 (酒館), 便當',
  'price_lunch': '-',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'holiday': '星期三'},
 {'rating': '3.62',
  'name': '船頭料理 魚莊',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46000234/',
  'area_genre': '都通車站 87m / 海鮮, 居酒屋 (酒館), 壽司',
  'price_lunch': '-',
  'price_dinner': 'JPY 6,000 - JPY 7,999',
  'holiday': '星期日'},
 {'rating': '3.09',
  'name': '鹿兒島黑豬涮涮鍋割烹 世樂',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46000613/',
  'area_genre': '甲東中學前車站 253m / 居酒屋 (酒館), 涮涮鍋, 海鮮',
  'price_lunch': '-',
  'price_dinner': 'JPY 8,000 - JPY 9,999',
  'holiday': '星期日'},
 {'rating': '3.14',
  'name': '鄉土爐端 Mizuki',
  'link': 'https://tabelog.com/tw/kagoshima/A4605/A460502/46016987/',
  'area_genre': '居酒屋 (酒館)',
  'price_lunch': 'JPY 3,000 - JPY 3,999',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'holiday': '星期日'},
 {'rating': '3.21',
  'name': 'THE ROOF rooftop bar & bistro',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46017667/',
  'area_genre': '甲東中學前車站 297m / 法式小酒館, 餐酒吧, 西式料理',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.32',
  'name': '定食飯男',
  'link': 'https://tabelog.com/tw/kagoshima/A4601/A460101/46016534/',
  'area_genre': '高见马场車站 114m / 食堂, 海鮮, 居酒屋 (酒館)',
  'price_lunch': '-',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'holiday': '星期三'}]

In [14]:
import pandas as pd

total_table = []
for i in range(2):
  page = i + 1
  table = download_page(page)
  df = pd.DataFrame(table)
  total_table.append(df)

total_df = pd.concat(total_table)
total_df

,rating,name,link,area_genre,price_lunch,price_dinner,holiday
0,3.59,燒肉上畜,https://tabelog.com/tw/kagoshima/A4601/A460101...,"都通車站 90m / 燒肉, 內臟類, 韓國料理","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-
1,3.76,豬排與、涮涮鍋。黑豚Fukuya,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 52m / 炸豬排, 涮涮鍋, 日式火鍋","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-
2,3.40,Miyama本舖 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 219m / 居酒屋 (酒館), 烤雞肉串, 燒肉",-,"JPY 4,000 - JPY 4,999",星期日
3,3.74,壽司處 Kimiya,https://tabelog.com/tw/kagoshima/A4601/A460101...,脇田車站 27m / 壽司,"JPY 4,000 - JPY 4,999","JPY 5,000 - JPY 5,999","星期三, 星期四"
4,3.19,味菜Minami,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 123m / 居酒屋 (酒館), 涮涮鍋, 海鮮","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-
5,3.24,炭火燒鳥Toriton,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 184m / 烤雞肉串, 居酒屋 (酒館), 海鮮",-,"JPY 3,000 - JPY 3,999",-
6,3.24,奄美啤酒廳,https://tabelog.com/tw/kagoshima/A4605/A460502...,"啤酒館, 郷土料理, 居酒屋 (酒館)",-,"JPY 2,000 - JPY 2,999",星期三
7,3.38,Rengaya,https://tabelog.com/tw/kagoshima/A4605/A460501...,燒肉,-,"JPY 3,000 - JPY 3,999",星期三
8,3.17,包廂燒肉 牛道 Hanare,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 224m / 燒肉, 涮涮鍋, 壽喜燒",-,"JPY 10,000 - JPY 14,999",-
9,3.43,黑豬涮涮鍋 雜炊之店 八幡,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 171m / 涮涮鍋, 居酒屋 (酒館), 郷土料理","JPY 1,000 - JPY 1,999","JPY 5,000 - JPY 5,999",-
10,3.09,鐵板 薊 鹿兒島店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 76m / 居酒屋 (酒館), 鐵板燒, 海鮮","JPY 3,000 - JPY 3,999","JPY 10,000 - JPY 14,999",-
11,3.15,日本料理 石原,https://tabelog.com/tw/kagoshima/A4601/A460101...,"朝日通車站 467m / 日本料理, 郷土料理","JPY 3,000 - JPY 3,999","JPY 8,000 - JPY 9,999",星期三
12,3.09,飲食處 官兵衛,https://tabelog.com/tw/kagoshima/A4605/A460502...,"郷土料理, 居酒屋 (酒館), 餐酒吧",-,"JPY 3,000 - JPY 3,999",星期三
13,3.03,Royco 窯烤料理與葡萄酒之店,https://tabelog.com/tw/kagoshima/A4601/A460101...,荒田八幡車站 107m / 義大利料理,"JPY 2,000 - JPY 2,999","JPY 5,000 - JPY 5,999",星期二
14,3.48,鹿兒島黑豚 六白亭,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 353m / 涮涮鍋, 居酒屋 (酒館), 炸豬排","JPY 1,000 - JPY 1,999","JPY 3,000 - JPY 3,999",-
15,3.51,熟成燒肉 Gyudo! 本店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 80m / 燒肉, 內臟類, 牛排","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-
16,3.09,鹿兒島縣產A5等級黑毛和牛 全席完全個室 牛一彩 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 367m / 燒肉, 壽喜燒, 涮涮鍋","JPY 1,000 - JPY 1,999","JPY 5,000 - JPY 5,999",-
17,3.01,大眾鳥酒場 Toriichizu 鹿兒島天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 203m / 居酒屋 (酒館), 烤雞肉串, 雞肉鍋","JPY 1,000 - JPY 1,999","JPY 2,000 - JPY 2,999",-
18,3.37,Mikan,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 237m / 居酒屋 (酒館), 涮涮鍋, 郷土料理",-,"JPY 4,000 - JPY 4,999",星期日
19,3.35,Miyama本舖 國分店,https://tabelog.com/tw/kagoshima/A4603/A460301...,"國分車站 708m / 居酒屋 (酒館), 烤雞肉串, 燒肉",-,"JPY 4,000 - JPY 4,999",-
0,3.39,燒酎 酒々藏,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 189m / 居酒屋 (酒館), 海鮮, 郷土料理",-,"JPY 3,000 - JPY 3,999",星期日
1,3.17,Higoya 鹿兒島本店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 219m / 居酒屋 (酒館), 豬肉涮涮鍋",-,"JPY 5,000 - JPY 5,999",星期日
2,3.54,吾愛人 中央站東口店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 45m / 居酒屋 (酒館), 涮涮鍋, 炸豬排",-,"JPY 4,000 - JPY 4,999",星期一
3,3.31,魚菜屋 朝次郎 AMU PLAZA鹿兒島店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央站前車站 130m / 居酒屋 (酒館), 海鮮, 海鮮蓋飯","JPY 1,000 - JPY 1,999","JPY 2,000 - JPY 2,999",-
4,3.29,薩摩 黑豬百寛,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央車站 289m / 居酒屋 (酒館), 涮涮鍋, 海鮮","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-
5,3.06,日本料理 Minato,https://tabelog.com/tw/kagoshima/A4601/A460101...,"郡元車站 1285m / 日本料理, 鰻魚, 郷土料理","JPY 3,000 - JPY 3,999","JPY 5,000 - JPY 5,999",-
6,None,近江牛 Horumon 畜産Sudaku 國分中央店,https://tabelog.com/tw/kagoshima/A4603/A460301...,"國分車站 651m / 燒肉, 內臟類, 居酒屋 (酒館)",-,"JPY 4,000 - JPY 4,999",-
7,3.54,Yakushimademinshuku yatteimashita,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 132m / 居酒屋 (酒館), 海鮮, 郷土料理",-,"JPY 4,000 - JPY 4,999",-
8,3.40,吾愛人 中央驛西口店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央車站 212m / 涮涮鍋, 郷土料理, 居酒屋 (酒館)",-,"JPY 4,000 - JPY 4,999",星期日
9,3.07,鹿兒島劇場,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 210m / 居酒屋 (酒館), 海鮮, 涮涮鍋","JPY 2,000 - JPY 2,999","JPY 2,000 - JPY 2,999",-
10,3.56,太郎壽司,https://tabelog.com/tw/kagoshima/A4602/A460203...,"阿久根車站 310m / 壽司, 海鮮, 鰻魚","JPY 2,000 - JPY 2,999","JPY 4,000 - JPY 4,999",-
11,3.61,炭火燒烤魚與、土鍋煮飯。定食屋 Ochawan,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 192m / 食堂, 酒店, 日本料理","JPY 2,000 - JPY 2,999",-,-
12,3.07,黑毛和牛專門店 牛排＆肉壽司 Kirishima牧場 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 78m / 牛排, 壽司","JPY 2,000 - JPY 2,999","JPY 6,000 - JPY 7,999",-
13,3.01,中央町 貴良,https://tabelog.com/tw/kagoshima/A4601/A460101...,都通車站 109m / 日本料理,"JPY 8,000 - JPY 9,999","JPY 15,000 - JPY 19,999",-
14,3.06,炭火燒肉內臟 Yokozuna Sanshirou 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 240m / 燒肉, 居酒屋 (酒館), 便當",-,"JPY 3,000 - JPY 3,999",星期三
15,3.62,船頭料理 魚莊,https://tabelog.com/tw/kagoshima/A4601/A460101...,"都通車站 87m / 海鮮, 居酒屋 (酒館), 壽司",-,"JPY 6,000 - JPY 7,999",星期日
16,3.09,鹿兒島黑豬涮涮鍋割烹 世樂,https://tabelog.com/tw/kagoshima/A4601/A460101...,"甲東中學前車站 253m / 居酒屋 (酒館), 涮涮鍋, 海鮮",-,"JPY 8,000 - JPY 9,999",星期日
17,3.14,鄉土爐端 Mizuki,https://tabelog.com/tw/kagoshima/A4605/A460502...,居酒屋 (酒館),"JPY 3,000 - JPY 3,999","JPY 3,000 - JPY 3,999",星期日
18,3.21,THE ROOF rooftop bar & bistro,https://tabelog.com/tw/kagoshima/A4601/A460101...,"甲東中學前車站 297m / 法式小酒館, 餐酒吧, 西式料理","JPY 2,000 - JPY 2,999","JPY 4,000 - JPY 4,999",-
19,3.32,定食飯男,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高见马场車站 114m / 食堂, 海鮮, 居酒屋 (酒館)",-,"JPY 3,000 - JPY 3,999",星期三

- pandas兩大操作
  -過濾操作: 帶入跟你資料筆數一樣多的True/False
  -轉換:

- Everything is an object
  - 所有東西一定具有型態，每種型態都有自己的操作
  - 型態dict: 操作:[key]
  - 以前說過，功能後面必加()
    - 型態: print操作:()
    - 功能是一種形態
      - 我是把幾句話變成一個SOP(型態)
      - 家小括號才是真的操作一遍SOP

In [ ]:
type(print(3))

3

NoneType

In [15]:
b = int
b(4.6)
def test(a):
    if a > 5:
        return int
    else:
        return round
test(3)(4.6)

5

In [16]:
# demo: apply
def func(n):
    return n * 2

total_df["rating"].astype(float).apply(func)

0     7.18
1     7.52
2     6.80
3     7.48
4     6.38
5     6.48
6     6.48
7     6.76
8     6.34
9     6.86
10    6.18
11    6.30
12    6.18
13    6.06
14    6.96
15    7.02
16    6.18
17    6.02
18    6.74
19    6.70
0     6.78
1     6.34
2     7.08
3     6.62
4     6.58
5     6.12
6      NaN
7     7.08
8     6.80
9     6.14
10    7.12
11    7.22
12    6.14
13    6.02
14    6.12
15    7.24
16    6.18
17    6.28
18    6.42
19    6.64
Name: rating, dtype: float64

In [17]:
def func(s):
    s_spl = s.split(" / ")
    ans = {
        "area":None,
        "genre":None
    }
    if len(s_spl) == 1:
        ans["genre"] = s_spl[0]
    else:
        ans["area"] = s_spl[0]
        ans["genre"] = s_spl[1]
    return pd.Series(ans)

total_df[["area", "genre"]] = total_df["area_genre"].apply(func)
total_df

,rating,name,link,area_genre,price_lunch,price_dinner,holiday,area,genre
0,3.59,燒肉上畜,https://tabelog.com/tw/kagoshima/A4601/A460101...,"都通車站 90m / 燒肉, 內臟類, 韓國料理","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-,都通車站 90m,"燒肉, 內臟類, 韓國料理"
1,3.76,豬排與、涮涮鍋。黑豚Fukuya,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 52m / 炸豬排, 涮涮鍋, 日式火鍋","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-,天文館通車站 52m,"炸豬排, 涮涮鍋, 日式火鍋"
2,3.40,Miyama本舖 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 219m / 居酒屋 (酒館), 烤雞肉串, 燒肉",-,"JPY 4,000 - JPY 4,999",星期日,天文館通車站 219m,"居酒屋 (酒館), 烤雞肉串, 燒肉"
3,3.74,壽司處 Kimiya,https://tabelog.com/tw/kagoshima/A4601/A460101...,脇田車站 27m / 壽司,"JPY 4,000 - JPY 4,999","JPY 5,000 - JPY 5,999","星期三, 星期四",脇田車站 27m,壽司
4,3.19,味菜Minami,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 123m / 居酒屋 (酒館), 涮涮鍋, 海鮮","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-,天文館通車站 123m,"居酒屋 (酒館), 涮涮鍋, 海鮮"
5,3.24,炭火燒鳥Toriton,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 184m / 烤雞肉串, 居酒屋 (酒館), 海鮮",-,"JPY 3,000 - JPY 3,999",-,天文館通車站 184m,"烤雞肉串, 居酒屋 (酒館), 海鮮"
6,3.24,奄美啤酒廳,https://tabelog.com/tw/kagoshima/A4605/A460502...,"啤酒館, 郷土料理, 居酒屋 (酒館)",-,"JPY 2,000 - JPY 2,999",星期三,None,"啤酒館, 郷土料理, 居酒屋 (酒館)"
7,3.38,Rengaya,https://tabelog.com/tw/kagoshima/A4605/A460501...,燒肉,-,"JPY 3,000 - JPY 3,999",星期三,None,燒肉
8,3.17,包廂燒肉 牛道 Hanare,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 224m / 燒肉, 涮涮鍋, 壽喜燒",-,"JPY 10,000 - JPY 14,999",-,天文館通車站 224m,"燒肉, 涮涮鍋, 壽喜燒"
9,3.43,黑豬涮涮鍋 雜炊之店 八幡,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 171m / 涮涮鍋, 居酒屋 (酒館), 郷土料理","JPY 1,000 - JPY 1,999","JPY 5,000 - JPY 5,999",-,高見橋車站 171m,"涮涮鍋, 居酒屋 (酒館), 郷土料理"
10,3.09,鐵板 薊 鹿兒島店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 76m / 居酒屋 (酒館), 鐵板燒, 海鮮","JPY 3,000 - JPY 3,999","JPY 10,000 - JPY 14,999",-,天文館通車站 76m,"居酒屋 (酒館), 鐵板燒, 海鮮"
11,3.15,日本料理 石原,https://tabelog.com/tw/kagoshima/A4601/A460101...,"朝日通車站 467m / 日本料理, 郷土料理","JPY 3,000 - JPY 3,999","JPY 8,000 - JPY 9,999",星期三,朝日通車站 467m,"日本料理, 郷土料理"
12,3.09,飲食處 官兵衛,https://tabelog.com/tw/kagoshima/A4605/A460502...,"郷土料理, 居酒屋 (酒館), 餐酒吧",-,"JPY 3,000 - JPY 3,999",星期三,None,"郷土料理, 居酒屋 (酒館), 餐酒吧"
13,3.03,Royco 窯烤料理與葡萄酒之店,https://tabelog.com/tw/kagoshima/A4601/A460101...,荒田八幡車站 107m / 義大利料理,"JPY 2,000 - JPY 2,999","JPY 5,000 - JPY 5,999",星期二,荒田八幡車站 107m,義大利料理
14,3.48,鹿兒島黑豚 六白亭,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 353m / 涮涮鍋, 居酒屋 (酒館), 炸豬排","JPY 1,000 - JPY 1,999","JPY 3,000 - JPY 3,999",-,高見橋車站 353m,"涮涮鍋, 居酒屋 (酒館), 炸豬排"
15,3.51,熟成燒肉 Gyudo! 本店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 80m / 燒肉, 內臟類, 牛排","JPY 1,000 - JPY 1,999","JPY 6,000 - JPY 7,999",-,天文館通車站 80m,"燒肉, 內臟類, 牛排"
16,3.09,鹿兒島縣產A5等級黑毛和牛 全席完全個室 牛一彩 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 367m / 燒肉, 壽喜燒, 涮涮鍋","JPY 1,000 - JPY 1,999","JPY 5,000 - JPY 5,999",-,天文館通車站 367m,"燒肉, 壽喜燒, 涮涮鍋"
17,3.01,大眾鳥酒場 Toriichizu 鹿兒島天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 203m / 居酒屋 (酒館), 烤雞肉串, 雞肉鍋","JPY 1,000 - JPY 1,999","JPY 2,000 - JPY 2,999",-,天文館通車站 203m,"居酒屋 (酒館), 烤雞肉串, 雞肉鍋"
18,3.37,Mikan,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 237m / 居酒屋 (酒館), 涮涮鍋, 郷土料理",-,"JPY 4,000 - JPY 4,999",星期日,天文館通車站 237m,"居酒屋 (酒館), 涮涮鍋, 郷土料理"
19,3.35,Miyama本舖 國分店,https://tabelog.com/tw/kagoshima/A4603/A460301...,"國分車站 708m / 居酒屋 (酒館), 烤雞肉串, 燒肉",-,"JPY 4,000 - JPY 4,999",-,國分車站 708m,"居酒屋 (酒館), 烤雞肉串, 燒肉"
0,3.39,燒酎 酒々藏,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 189m / 居酒屋 (酒館), 海鮮, 郷土料理",-,"JPY 3,000 - JPY 3,999",星期日,天文館通車站 189m,"居酒屋 (酒館), 海鮮, 郷土料理"
1,3.17,Higoya 鹿兒島本店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 219m / 居酒屋 (酒館), 豬肉涮涮鍋",-,"JPY 5,000 - JPY 5,999",星期日,天文館通車站 219m,"居酒屋 (酒館), 豬肉涮涮鍋"
2,3.54,吾愛人 中央站東口店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高見橋車站 45m / 居酒屋 (酒館), 涮涮鍋, 炸豬排",-,"JPY 4,000 - JPY 4,999",星期一,高見橋車站 45m,"居酒屋 (酒館), 涮涮鍋, 炸豬排"
3,3.31,魚菜屋 朝次郎 AMU PLAZA鹿兒島店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央站前車站 130m / 居酒屋 (酒館), 海鮮, 海鮮蓋飯","JPY 1,000 - JPY 1,999","JPY 2,000 - JPY 2,999",-,鹿兒島中央站前車站 130m,"居酒屋 (酒館), 海鮮, 海鮮蓋飯"
4,3.29,薩摩 黑豬百寛,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央車站 289m / 居酒屋 (酒館), 涮涮鍋, 海鮮","JPY 1,000 - JPY 1,999","JPY 4,000 - JPY 4,999",-,鹿兒島中央車站 289m,"居酒屋 (酒館), 涮涮鍋, 海鮮"
5,3.06,日本料理 Minato,https://tabelog.com/tw/kagoshima/A4601/A460101...,"郡元車站 1285m / 日本料理, 鰻魚, 郷土料理","JPY 3,000 - JPY 3,999","JPY 5,000 - JPY 5,999",-,郡元車站 1285m,"日本料理, 鰻魚, 郷土料理"
6,None,近江牛 Horumon 畜産Sudaku 國分中央店,https://tabelog.com/tw/kagoshima/A4603/A460301...,"國分車站 651m / 燒肉, 內臟類, 居酒屋 (酒館)",-,"JPY 4,000 - JPY 4,999",-,國分車站 651m,"燒肉, 內臟類, 居酒屋 (酒館)"
7,3.54,Yakushimademinshuku yatteimashita,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 132m / 居酒屋 (酒館), 海鮮, 郷土料理",-,"JPY 4,000 - JPY 4,999",-,天文館通車站 132m,"居酒屋 (酒館), 海鮮, 郷土料理"
8,3.40,吾愛人 中央驛西口店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"鹿兒島中央車站 212m / 涮涮鍋, 郷土料理, 居酒屋 (酒館)",-,"JPY 4,000 - JPY 4,999",星期日,鹿兒島中央車站 212m,"涮涮鍋, 郷土料理, 居酒屋 (酒館)"
9,3.07,鹿兒島劇場,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 210m / 居酒屋 (酒館), 海鮮, 涮涮鍋","JPY 2,000 - JPY 2,999","JPY 2,000 - JPY 2,999",-,天文館通車站 210m,"居酒屋 (酒館), 海鮮, 涮涮鍋"
10,3.56,太郎壽司,https://tabelog.com/tw/kagoshima/A4602/A460203...,"阿久根車站 310m / 壽司, 海鮮, 鰻魚","JPY 2,000 - JPY 2,999","JPY 4,000 - JPY 4,999",-,阿久根車站 310m,"壽司, 海鮮, 鰻魚"
11,3.61,炭火燒烤魚與、土鍋煮飯。定食屋 Ochawan,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 192m / 食堂, 酒店, 日本料理","JPY 2,000 - JPY 2,999",-,-,天文館通車站 192m,"食堂, 酒店, 日本料理"
12,3.07,黑毛和牛專門店 牛排＆肉壽司 Kirishima牧場 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 78m / 牛排, 壽司","JPY 2,000 - JPY 2,999","JPY 6,000 - JPY 7,999",-,天文館通車站 78m,"牛排, 壽司"
13,3.01,中央町 貴良,https://tabelog.com/tw/kagoshima/A4601/A460101...,都通車站 109m / 日本料理,"JPY 8,000 - JPY 9,999","JPY 15,000 - JPY 19,999",-,都通車站 109m,日本料理
14,3.06,炭火燒肉內臟 Yokozuna Sanshirou 天文館店,https://tabelog.com/tw/kagoshima/A4601/A460101...,"天文館通車站 240m / 燒肉, 居酒屋 (酒館), 便當",-,"JPY 3,000 - JPY 3,999",星期三,天文館通車站 240m,"燒肉, 居酒屋 (酒館), 便當"
15,3.62,船頭料理 魚莊,https://tabelog.com/tw/kagoshima/A4601/A460101...,"都通車站 87m / 海鮮, 居酒屋 (酒館), 壽司",-,"JPY 6,000 - JPY 7,999",星期日,都通車站 87m,"海鮮, 居酒屋 (酒館), 壽司"
16,3.09,鹿兒島黑豬涮涮鍋割烹 世樂,https://tabelog.com/tw/kagoshima/A4601/A460101...,"甲東中學前車站 253m / 居酒屋 (酒館), 涮涮鍋, 海鮮",-,"JPY 8,000 - JPY 9,999",星期日,甲東中學前車站 253m,"居酒屋 (酒館), 涮涮鍋, 海鮮"
17,3.14,鄉土爐端 Mizuki,https://tabelog.com/tw/kagoshima/A4605/A460502...,居酒屋 (酒館),"JPY 3,000 - JPY 3,999","JPY 3,000 - JPY 3,999",星期日,None,居酒屋 (酒館)
18,3.21,THE ROOF rooftop bar & bistro,https://tabelog.com/tw/kagoshima/A4601/A460101...,"甲東中學前車站 297m / 法式小酒館, 餐酒吧, 西式料理","JPY 2,000 - JPY 2,999","JPY 4,000 - JPY 4,999",-,甲東中學前車站 297m,"法式小酒館, 餐酒吧, 西式料理"
19,3.32,定食飯男,https://tabelog.com/tw/kagoshima/A4601/A460101...,"高见马场車站 114m / 食堂, 海鮮, 居酒屋 (酒館)",-,"JPY 3,000 - JPY 3,999",星期三,高见马场車站 114m,"食堂, 海鮮, 居酒屋 (酒館)"